### ISSUE TITLE
6. Images - differentiate steps: calculate text alternative; determine whether equivalent

### ISSUE THREAD

**Issue by drewnielson** [Section508Coordinators/ICTTestingBaseline#213] opened 2020-05-28 17:20 UTC
Consider dividing step into two separate steps. Also raises question of similar approach in other tests to reflect more detailed steps that may be delineated in Test Case steps.

**Comment by kengdoj** [comment] 2020-06-02 21:01
@drewnielson , is this the same as Issue #208?

**Comment by drewnielson** [comment] 2020-06-03 15:36
Ummm, maybe? Yes, can probably get rid of this one specifically for 6. Images and just cover it under #208 as the broader issue for other Baseline tests where the same step would be necessary.

**Comment by kengdoj** [comment] 2020-06-04 22:28
Ok, this is a duplicate of #208 so closing.

**Closed by kengdoj** 2020-06-04 22:28 UTC
